// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAT6X_pxrvITA_fJBMznk-rBh2LAFJYV4',
    appId: '1:409741448445:web:348ce4aa0170f6c6535a94',
    messagingSenderId: '409741448445',
    projectId: 'chat-app-c8d95',
    authDomain: 'chat-app-c8d95.firebaseapp.com',
    storageBucket: 'chat-app-c8d95.appspot.com',
    measurementId: 'G-R0T4PBD51E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0u4pZyObbZB3v_Hr8FVMkoKFo6C4-bYI',
    appId: '1:409741448445:android:d33edb158398d7d4535a94',
    messagingSenderId: '409741448445',
    projectId: 'chat-app-c8d95',
    storageBucket: 'chat-app-c8d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBT81VAyHbW_Oi0nKqhdQ3zVKOCUh7JQc',
    appId: '1:409741448445:ios:2edf1f2d13ebdd4a535a94',
    messagingSenderId: '409741448445',
    projectId: 'chat-app-c8d95',
    storageBucket: 'chat-app-c8d95.appspot.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBT81VAyHbW_Oi0nKqhdQ3zVKOCUh7JQc',
    appId: '1:409741448445:ios:2edf1f2d13ebdd4a535a94',
    messagingSenderId: '409741448445',
    projectId: 'chat-app-c8d95',
    storageBucket: 'chat-app-c8d95.appspot.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAT6X_pxrvITA_fJBMznk-rBh2LAFJYV4',
    appId: '1:409741448445:web:7aeaf4258509003d535a94',
    messagingSenderId: '409741448445',
    projectId: 'chat-app-c8d95',
    authDomain: 'chat-app-c8d95.firebaseapp.com',
    storageBucket: 'chat-app-c8d95.appspot.com',
    measurementId: 'G-TGWCF6CFY5',
  );
}
